import type { Movie } from "./types"

export const allMovies: Movie[] = [
  // ACTION MOVIES
  {
    id: "1",
    title: "Pushpa 2: The Rule",
    genre: "Action/Drama",
    duration: "3h 20m",
    rating: "9.1",
    image: "/pushpa-2-the-rule-poster.jpg",
    description: "The clash is on as Pushpa faces his biggest nemesis yet in this action-packed sequel.",
    showtimes: ["10:00 AM", "1:30 PM", "5:00 PM", "8:30 PM", "11:00 PM"],
    language: "Telugu/Hindi",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
  },
  {
    id: "2",
    title: "Animal",
    genre: "Action/Thriller",
    duration: "3h 21m",
    rating: "8.8",
    image: "/animal-movie-poster.jpg",
    description: "A son's undying love for his father leads him down a dangerous path of vengeance.",
    showtimes: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Pune", "Ahmedabad", "Jaipur"],
  },
  {
    id: "3",
    title: "Salaar",
    genre: "Action",
    duration: "2h 55m",
    rating: "8.9",
    image: "/salaar-movie-poster.jpg",
    description: "A gang leader tries to keep a promise made to his dying friend and takes on the bloody crime world.",
    showtimes: ["10:30 AM", "2:00 PM", "5:30 PM", "9:00 PM"],
    language: "Kannada/Telugu/Hindi",
    cities: ["Bangalore", "Hyderabad", "Chennai", "Kochi", "Mysore"],
  },
  {
    id: "6",
    title: "Tiger 3",
    genre: "Action/Spy",
    duration: "2h 35m",
    rating: "8.4",
    image: "/tiger-3-movie-poster.jpg",
    description: "Tiger and Zoya are back in a thrilling spy adventure that takes them across the globe.",
    showtimes: ["10:00 AM", "1:00 PM", "4:30 PM", "8:00 PM", "11:30 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Bangalore", "Pune", "Surat"],
  },
  {
    id: "8",
    title: "Leo",
    genre: "Action/Thriller",
    duration: "2h 44m",
    rating: "8.7",
    image: "/leo-movie-poster-vijay-thalapathy.jpg",
    description: "A café owner with a mysterious past becomes the target of a ruthless drug cartel.",
    showtimes: ["10:30 AM", "2:00 PM", "5:30 PM", "9:00 PM"],
    language: "Tamil/Telugu/Hindi",
    cities: ["Chennai", "Bangalore", "Hyderabad", "Kochi", "Coimbatore"],
  },
  {
    id: "9",
    title: "Gadar 2",
    genre: "Action/Drama",
    duration: "2h 50m",
    rating: "8.3",
    image: "/gadar-2-movie-poster-sunny-deol.jpg",
    description: "Tara Singh goes to Pakistan to bring back his son, facing the ultimate test of love and courage.",
    showtimes: ["11:30 AM", "3:00 PM", "6:30 PM", "10:00 PM"],
    language: "Hindi",
    cities: ["Delhi", "Mumbai", "Chandigarh", "Jaipur", "Lucknow"],
  },
  {
    id: "10",
    title: "Pathaan",
    genre: "Action/Spy",
    duration: "2h 26m",
    rating: "8.6",
    image: "/pathaan-movie-poster-shah-rukh-khan-spy.jpg",
    description: "An exiled RAW agent is brought back to stop a mercenary organization planning an attack on India.",
    showtimes: ["10:00 AM", "1:30 PM", "5:00 PM", "8:30 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Kolkata"],
  },
  {
    id: "11",
    title: "Jailer",
    genre: "Action/Comedy",
    duration: "2h 48m",
    rating: "8.8",
    image: "/jailer-movie-poster-rajinikanth.jpg",
    description: "A retired jailer goes on a revenge mission against a gang that kidnapped his son.",
    showtimes: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
    language: "Tamil/Telugu/Hindi",
    cities: ["Chennai", "Bangalore", "Hyderabad", "Kochi", "Madurai"],
  },
  {
    id: "13",
    title: "Mission: Impossible - Dead Reckoning",
    genre: "Action/Thriller",
    duration: "2h 43m",
    rating: "8.9",
    image: "/mission-impossible-dead-reckoning-tom-cruise-action-thriller.jpg",
    description: "Ethan Hunt faces his most dangerous mission yet as he races against time to save humanity.",
    showtimes: ["10:00 AM", "1:30 PM", "5:00 PM", "8:30 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
  },
  {
    id: "14",
    title: "John Wick: Chapter 4",
    genre: "Action/Thriller",
    duration: "2h 49m",
    rating: "9.0",
    image: "/john-wick-chapter-4-keanu-reeves-action-poster.jpg",
    description: "John Wick discovers a path to defeating The High Table but must face off against a new enemy.",
    showtimes: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Pune", "Kolkata"],
  },

  // THRILLER MOVIES
  {
    id: "4",
    title: "Jawan",
    genre: "Action/Thriller",
    duration: "2h 49m",
    rating: "9.0",
    image: "/jawan-movie-poster.jpg",
    description: "A high-octane action thriller which outlines the emotional journey of a man set out on a mission.",
    showtimes: ["12:00 PM", "3:30 PM", "7:00 PM", "10:30 PM"],
    language: "Hindi/Tamil/Telugu",
    cities: ["Mumbai", "Delhi", "Kolkata", "Chennai", "Hyderabad"],
  },
  {
    id: "15",
    title: "Bholaa",
    genre: "Action/Thriller",
    duration: "2h 24m",
    rating: "8.2",
    image: "/bholaa-ajay-devgn-action-thriller-poster.jpg",
    description: "A prisoner races against time to save his daughter and help cops fight off a drug cartel siege.",
    showtimes: ["11:00 AM", "2:00 PM", "5:30 PM", "9:00 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Lucknow", "Patna", "Jaipur"],
  },
  {
    id: "16",
    title: "Oppenheimer",
    genre: "Thriller/Biography",
    duration: "3h 00m",
    rating: "9.3",
    image: "/oppenheimer-cillian-murphy-christopher-nolan-atomic-bomb.jpg",
    description:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    showtimes: ["10:00 AM", "2:00 PM", "6:00 PM", "9:30 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Kolkata"],
  },
  {
    id: "17",
    title: "The Killer",
    genre: "Thriller/Action",
    duration: "1h 58m",
    rating: "8.5",
    image: "/the-killer-michael-fassbender-david-fincher-assassin.jpg",
    description:
      "A methodical assassin faces a crisis when a mission goes wrong and must hunt those who want him dead.",
    showtimes: ["11:30 AM", "3:00 PM", "6:30 PM", "10:00 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Chennai", "Pune"],
  },

  // HORROR MOVIES
  {
    id: "18",
    title: "Stree 2",
    genre: "Horror/Comedy",
    duration: "2h 29m",
    rating: "8.6",
    image: "/stree-2-shraddha-kapoor-rajkummar-rao-horror-comedy.jpg",
    description: "The spirit of Stree returns to haunt the town once again in this horror-comedy sequel.",
    showtimes: ["12:00 PM", "3:30 PM", "7:00 PM", "10:30 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Bangalore", "Indore", "Bhopal"],
  },
  {
    id: "19",
    title: "Insidious: The Red Door",
    genre: "Horror/Thriller",
    duration: "1h 47m",
    rating: "7.8",
    image: "/insidious-red-door-horror-supernatural-thriller.jpg",
    description: "The Lambert family faces new supernatural threats as they venture further into The Further.",
    showtimes: ["11:00 AM", "2:00 PM", "5:00 PM", "8:00 PM", "11:00 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Kolkata"],
  },
  {
    id: "20",
    title: "The Nun II",
    genre: "Horror/Mystery",
    duration: "1h 50m",
    rating: "8.0",
    image: "/the-nun-2-horror-valak-demon-nun-dark.jpg",
    description: "Sister Irene must confront the demonic nun Valak once again in this terrifying sequel.",
    showtimes: ["10:30 AM", "1:30 PM", "4:30 PM", "7:30 PM", "10:30 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Chennai", "Bangalore", "Pune"],
  },
  {
    id: "21",
    title: "Tumbbad",
    genre: "Horror/Fantasy",
    duration: "1h 44m",
    rating: "9.1",
    image: "/tumbbad-sohum-shah-horror-mythology-dark-mansion.jpg",
    description: "A man's greed for gold leads him down a dangerous path involving an ancient demon.",
    showtimes: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
    language: "Hindi/Marathi",
    cities: ["Mumbai", "Pune", "Delhi", "Bangalore", "Hyderabad"],
  },

  // DRAMA MOVIES
  {
    id: "7",
    title: "12th Fail",
    genre: "Drama/Biography",
    duration: "2h 27m",
    rating: "9.2",
    image: "/12th-fail-movie-poster.jpg",
    description: "The inspiring true story of an IPS officer who overcomes extreme poverty to serve his country.",
    showtimes: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
    language: "Hindi",
    cities: ["Delhi", "Mumbai", "Bhopal", "Indore", "Patna"],
  },
  {
    id: "22",
    title: "Sam Bahadur",
    genre: "Drama/Biography",
    duration: "2h 30m",
    rating: "8.7",
    image: "/sam-bahadur-vicky-kaushal-army-uniform-military.jpg",
    description: "The inspiring journey of India's first Field Marshal Sam Manekshaw.",
    showtimes: ["10:00 AM", "1:30 PM", "5:00 PM", "8:30 PM"],
    language: "Hindi",
    cities: ["Delhi", "Mumbai", "Chandigarh", "Bangalore", "Pune"],
  },
  {
    id: "23",
    title: "The Killers of the Flower Moon",
    genre: "Drama/Crime",
    duration: "3h 26m",
    rating: "9.1",
    image: "/killers-of-the-flower-moon-leonardo-dicaprio-rober.jpg",
    description: "FBI investigates a series of murders of wealthy Osage people in 1920s Oklahoma.",
    showtimes: ["10:00 AM", "2:30 PM", "7:00 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Kolkata", "Chennai"],
  },
  {
    id: "24",
    title: "The Kashmir Files",
    genre: "Drama/History",
    duration: "2h 50m",
    rating: "8.9",
    image: "/the-kashmir-files-anupam-kher-dramatic-emotional.jpg",
    description: "A heartbreaking tale revealing the exodus of Kashmiri Hindus in the 1990s.",
    showtimes: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
    language: "Hindi",
    cities: ["Delhi", "Mumbai", "Jammu", "Chandigarh", "Lucknow"],
  },

  // COMEDY MOVIES
  {
    id: "5",
    title: "Dunki",
    genre: "Comedy/Drama",
    duration: "2h 41m",
    rating: "8.5",
    image: "/dunki-movie-poster.jpg",
    description: "A hilarious and heartwarming tale of friends who want to migrate to London through illegal routes.",
    showtimes: ["11:30 AM", "3:00 PM", "6:30 PM", "10:00 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Chandigarh", "Amritsar", "Lucknow"],
  },
  {
    id: "25",
    title: "Bhediya",
    genre: "Comedy/Horror",
    duration: "2h 36m",
    rating: "8.1",
    image: "/bhediya-varun-dhawan-werewolf-transformation-comed.jpg",
    description: "A man gets bitten by a wolf and discovers he's turning into a werewolf in this horror-comedy.",
    showtimes: ["11:00 AM", "2:00 PM", "5:30 PM", "9:00 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Bangalore", "Pune", "Hyderabad"],
  },
  {
    id: "26",
    title: "Dream Girl 2",
    genre: "Comedy/Romance",
    duration: "2h 19m",
    rating: "7.9",
    image: "/dream-girl-2-ayushmann-khurrana-colorful-comedy-po.jpg",
    description: "Karam returns with his female alter-ego voice in this hilarious comedy of errors.",
    showtimes: ["12:00 PM", "3:00 PM", "6:30 PM", "10:00 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Jaipur", "Lucknow", "Indore"],
  },
  {
    id: "27",
    title: "Guardians of the Galaxy Vol. 3",
    genre: "Action/Comedy/Sci-Fi",
    duration: "2h 30m",
    rating: "8.8",
    image: "/guardians-of-the-galaxy-vol-3-marvel-space-colorfu.jpg",
    description: "The Guardians embark on a mission to protect one of their own in this emotional finale.",
    showtimes: ["10:30 AM", "1:30 PM", "4:30 PM", "7:30 PM", "10:30 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
  },

  // ROMANCE MOVIES
  {
    id: "12",
    title: "Rocky Aur Rani Kii Prem Kahaani",
    genre: "Romance/Drama",
    duration: "2h 48m",
    rating: "8.2",
    image: "/rocky-aur-rani-movie-poster-ranveer-singh-alia-bha.jpg",
    description: "Two contrasting families clash when their children fall in love in this grand romantic saga.",
    showtimes: ["12:00 PM", "3:30 PM", "7:00 PM", "10:30 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Kolkata", "Bangalore", "Pune"],
  },
  {
    id: "28",
    title: "Tu Jhoothi Main Makkaar",
    genre: "Romance/Comedy",
    duration: "2h 44m",
    rating: "7.8",
    image: "/tu-jhoothi-main-makkaar-ranbir-kapoor-shraddha-romantic-comedy.jpg",
    description: "A modern love story about a man who helps couples break up, until he falls in love himself.",
    showtimes: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Bangalore", "Pune", "Ahmedabad"],
  },
  {
    id: "29",
    title: "Zara Hatke Zara Bachke",
    genre: "Romance/Comedy",
    duration: "2h 12m",
    rating: "8.0",
    image: "/zara-hatke-zara-bachke-vicky-kaushal-sara-ali-khan-romantic.jpg",
    description: "A couple's plan to divorce to get separate houses leads to hilarious complications.",
    showtimes: ["12:00 PM", "3:00 PM", "6:30 PM", "10:00 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Indore", "Bhopal", "Lucknow"],
  },

  // SCI-FI MOVIES
  {
    id: "30",
    title: "Dune: Part Two",
    genre: "Sci-Fi/Adventure",
    duration: "2h 46m",
    rating: "9.2",
    image: "/dune-part-two-timothee-chalamet-desert-sci-fi-epic.jpg",
    description:
      "Paul Atreides unites with Chani and the Fremen to seek revenge against those who destroyed his family.",
    showtimes: ["10:00 AM", "1:30 PM", "5:00 PM", "8:30 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
  },
  {
    id: "31",
    title: "The Creator",
    genre: "Sci-Fi/Thriller",
    duration: "2h 13m",
    rating: "8.5",
    image: "/the-creator-john-david-washington-ai-robot-sci-fi.jpg",
    description:
      "An ex-special forces agent is recruited to hunt down the Creator of advanced AI amid a war between humans and robots.",
    showtimes: ["11:00 AM", "2:00 PM", "5:30 PM", "9:00 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Pune", "Hyderabad"],
  },
  {
    id: "32",
    title: "Avatar: The Way of Water",
    genre: "Sci-Fi/Adventure",
    duration: "3h 12m",
    rating: "9.0",
    image: "/avatar-way-of-water-james-cameron-pandora-ocean-blue.jpg",
    description: "Jake Sully and Neytiri have formed a family and must protect their children from a returning threat.",
    showtimes: ["10:00 AM", "2:00 PM", "6:00 PM", "9:30 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
  },
  {
    id: "33",
    title: "Spider-Man: Across the Spider-Verse",
    genre: "Animation/Sci-Fi/Action",
    duration: "2h 20m",
    rating: "9.1",
    image: "/spider-man-across-spider-verse-miles-morales-multiverse-animation.jpg",
    description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People.",
    showtimes: ["11:30 AM", "2:30 PM", "5:30 PM", "8:30 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Kolkata"],
  },
  {
    id: "34",
    title: "Brahmastra",
    genre: "Sci-Fi/Fantasy/Action",
    duration: "2h 47m",
    rating: "8.3",
    image: "/brahmastra-ranbir-kapoor-alia-bhatt-fantasy-fire-power.jpg",
    description: "A young man with the power of fire embarks on a journey to protect an ancient weapon.",
    showtimes: ["10:30 AM", "2:00 PM", "5:30 PM", "9:00 PM"],
    language: "Hindi",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Kolkata"],
  },
  {
    id: "35",
    title: "Interstellar",
    genre: "Sci-Fi/Drama",
    duration: "2h 49m",
    rating: "9.4",
    image: "/interstellar-matthew-mcconaughey-space-wormhole-nolan.jpg",
    description: "A team of explorers travel through a wormhole in space to ensure humanity's survival.",
    showtimes: ["10:00 AM", "2:00 PM", "6:00 PM", "10:00 PM"],
    language: "English",
    cities: ["Mumbai", "Delhi", "Bangalore", "Chennai", "Pune"],
  },
]
